### ISSUE TITLE
propel 2

### ISSUE THREAD

**Issue by aviqbaihaqy** [badlamer/UuidBehavior#2]
i am following error in propel 2 uding composer and autoload :

[Propel\Generator\Exception\BehaviorNotFoundException]
  Unknown behavior "uuid". You may try running `composer update` or passing the `--composer-dir` option.

**Comment by badlamer** [comment]
Propel2 It is not supported at this time

**Comment by stevleibelt** [comment]
Since [propel2](https://github.com/propelorm/Propel2) is already marked as deprecated in favor of the upcoming [propel3](https://github.com/propelorm/Propel3), I suggest to close this ticket :-).
